### ISSUE TITLE
Bees Don't Enter Hive, Even Outside Winter (And Config Options)

### ISSUE THREAD

**Issue by RandomMcSomethin** [Harvest-Festival/Simply-Seasons#3]
Bee do not enter their hives, even when it is not wintertime.  I have Resourceful Bees installed, and it seems as though the vanilla bees are the only ones affected by this.

On that note, I suggest making bee hibernation configurable.

**Comment by joshiejack** [comment]
Do you mean leave? I wonder if when I fixed the mod crashing with resourceful bees if that broke it. (I'd have to do special support to make theirs work)

**Comment by joshiejack** [comment]
Also it may depend on biome?

**Comment by RandomMcSomethin** [comment]
The vanilla bees just never enter the hive.  I tried this in a plains biome.  I'll check again to see if it's still happening.

**Comment by joshiejack** [comment]
If you have it in a pack with other mods can you check if it works with just simply seasons/penguin lib.

**Comment by RandomMcSomethin** [comment]
Okay, so I just tested it on a world with those two mods alone, and the bees still show issues.  They wander aimlessly, refusing even to pollinate flowers.

**Comment by joshiejack** [comment]
Okay try this one with just my mods (it seemed to help for me) and then try it with resourceful bees. If it works with just mine and not with theirs. I'll just disable my bee functionality if their mod is detected (until I can find the time to actually support it properly).

https://jenkins.joshiejack.uk/job/Simply-Seasons/21/
